# Makefile

# Name of the script
SCRIPT_NAME = scan_directory.sh

# The 'all' rule is the default. It provides usage instructions.
.PHONY: all
all:
	@echo "Usage: make export-repo TARGET=<directory>"
	@echo "Example: make export-repo TARGET=apps/todo-angular"

# The 'export-repo' rule takes the directory as an argument.
# example:
# make export-repo TARGET=apps/todo-angular
#
.PHONY: export-repo
export-repo:
ifeq ($(TARGET),)
	@echo "Error: The TARGET argument was not provided."
	@echo "Usage: make export-repo TARGET=<directory>"
	@echo "Example: make export-repo TARGET=apps/todo-angular"
	@exit 1
endif
	@echo "Scanning directory '$(TARGET)' and generating output file..."
	# Calls the script, passing the target directory and the output filename.
	# The output filename is generated by replacing slashes with hyphens.
	./scripts/$(SCRIPT_NAME) $(TARGET) $(subst /,-,$(TARGET)).assistant.txt
	@echo "File generated: $(subst /,-,$(TARGET)).txt"
